input_file: test_input_simple.md
output_file: test_substep_output.md
prompts:
  prompt 1:
    name: main_step_one
    prompt_file: test_simple_prompt.json
    temperature: 0.3
  prompt 1.1:
    name: substep_one_one
    prompt_file: test_simple_prompt.json
    temperature: 0.4
  prompt 1.2:
    name: substep_one_two
    prompt_file: test_simple_prompt.json
    temperature: 0.5
  prompt 2:
    name: main_step_two
    prompt_file: test_simple_prompt.json
    temperature: 0.6